# Generated by Django 4.1.5 on 2023-01-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
